config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'calendars#index', as: 'home'

  resources :calendars
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :check_time

  def check_time(day, time, event)
    # If the date is not in the range return false
    if event.start_time.strftime("%Y-%m-%d") > day.to_s or event.end_time.strftime("%Y-%m-%d") < day.to_s
      return false
    end

    start_time = event.start_time.hour
    end_time = event.end_time.hour

    # Following if statements are to change time value for AM and PM
    if event.start_meridian == "PM" and event.start_time != 12
      start_time = event.start_time.hour + 12
    end
    if event.end_meridian == "PM" and event.end_time != 12
      end_time = event.end_time.hour + 12
    end
    if event.start_meridian == "AM" and event.start_time == 12
      start_time = event.start_time.hour - 12
    end
    if event.end_meridian == "AM" and event.end_time == 12
      end_time = event.end_time.hour - 12
    end

    # if one-day event
    if event.start_time.strftime("%Y-%m-%d") == event.end_time.strftime("%Y-%m-%d")
      # Check if time is in the range
      if start_time <= time and time < end_time
        return true
      else
        return false
      end
    # if multi-day event
    else
      if start_time > time and event.start_time.strftime("%Y-%m-%d") == day.to_s
        return false
      end
      if end_time <= time and event.end_time.strftime("%Y-%m-%d") == day.to_s
        return false
      end
      return true
    end

  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  # this function is for the root page
  
  def index
    @events = Event.all
    @days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    @times = ["12:00 am", "1:00 am", "2:00 am", "3:00 am", "4:00 am", "5:00 am", "6:00 am", "7:00 am", "8:00 am", "9:00 am", "10:00 am", "11:00 am", "12:00 pm", "1:00 pm", "2:00 pm", "3:00 pm", "4:00 pm", "5:00 pm", "6:00 pm", "7:00 pm", "8:00 pm", "9:00 pm", "10:00 pm", "11:00 pm"]
	@week = 0
  
  end
  
  def addweek
    @week = @week + 1
    redirect_to :controller => 'calendars', action: 'index'
  end
  
  def subweek
    @week = @week - 1
    redirect_to :controller => 'calendars', action: 'index'
  end
  
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all
  end
  def show
    @event = Event.find(params[:id])
  end
  
  # this function shows the events/new page.
  def new
	@event = Event.new
	
  end
  
  # this function is for creating new event based on Event Model.
  def create
    # creates the event.
    @event = Event.new(event_params)

    # save to database.
    if @event.save
		# redirects to events page.
		redirect_to events_path, :notice => "Your event has been saved"
	else
		render "new"
	end
  end
  
  # this function shows in the events/id#/edit.
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
	
    @event = Event.find(params[:id])
	if @event.update_attributes(params[:event])
		redirect_to events_path, :notice => "Updated"
		
		# redirect_to :controller => 'calendars', action: 'index'
	else
		render "edit"
	end
  end

  # this function goes with edit and destroys event.
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to :controller => 'calendars', action: 'index'
  end
  
  
  # this function takes requirements for what create function should take in
  private def event_params
    params.require(:event).permit(:title, :start_time, :start_meridian, :end_time, :end_meridian)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/calendars/index.html.erb
<!-- Shows as homepage -->
<html>
  <head>
    <h1>Welcome to Whenisbest!</h1>
  </head>

  <body>
    <!-- All events are listed here -->

    <li><%= link_to "Add Event", new_event_path %> </li>
	
	<li><%= link_to "Events List", events_path %> </li>
	
    <h3> Current Time </h3>

    <%= date_today = Date.today  + (@week * 7)%>
    <%= day_today = Date.today.strftime('%A').to_s %>

    <%= start_week = date_today.at_beginning_of_week %>
    <%= end_week = date_today.at_end_of_week %>

    <h3>These are the events submitted so far</h3>

      <!-- Calendar starts here -->

      <div style = "width: 100%; height:100%">
        <div style ="background-color: rgb(0, 162, 232); width:100%; height: 100%">
          <button class="button">Back</button>
          <button class="button">Forward</button>
          <div class="wrapper">
            <form name = "Time">
              <select id = "dateTime" name = "Timetable">
                <option value = "1" selected>Week</option>
                <option value = "2">Day</option>
                <option value = "3">Month</option>
                <option value = "4">Year</option>
              </select>
            </form>
          </div>
        </div>

        <div>
          <table class ="table">
            <% for i in 0..24 do %>
              <tr>
              <% for j in 0..7 do %>

                <!-- print out day -->
                <% if i==0  and j!=0 %>
                  <td class = "regular">
                    <%= @days[j-1] %> <br>
                    <%= start_week + (j-1).days %>
                  </td>

                <!-- print out time -->
                <% elsif j==0 and i >0 %>
                  <td class = "regular">
                    <%= @times[i-1]%>
                  </td>

                <!-- print out empty cell -->
                <% else %>
                  <% found_events = [] %>
                  <% @events.each do |event| %>
                    <!-- First event in the events list is Nil -->
                    <!-- We should fix this -->
                    <% next if event.start_time.class == NilClass %>
                    <% if  check_time(start_week+(j-1).days, i-1, event) %>
                      <% found_events.push(event) %>
                    <% end %>
                  <% end %>
                  <% if found_events.length != 0 %>
                    <td class = "fill">
                      <!-- Print out all the found events -->
                      <% found_events.each do |found_event| %>
                        <%= link_to found_event.title, edit_event_path(found_event) %>
                      <% end %>
                    </td>
                  <% else %>
                    <!-- This is when no events are found in this cell -->
                    <td class = "regular"></td>
                  <% end %>
                <% end %>

              <% end %>
              </tr>
            <% end %>
          </table>
        </div>
      </div>


      <script>
            function myFunction() {
                var popup = document.getElementById("myPopup");
                popup.classList.toggle("show");
            }
      </script>


  </body>
</html>

app/views/events/edit.html.erb
<!-- Shows in events/id#/edit -->
<h2>Edit: <%= @event.title %></h2>

<%= form_for @event do |f| %>
  <p>
    <%=f.label :title%>
    <%=f.text_field :title%>
  </p>

  <p>
    <%=f.label :start_time%>
    <%=f.text_field :start_time%>
  </p>

  <p>
    <%=f.label :start_meridian%>
    <%=f.text_field :start_meridian%>
  </p>

  <p>
    <%=f.label :end_time%>
    <%=f.text_field :end_time%>
  </p>

  <p>
    <%=f.label :end_meridian%>
    <%=f.text_field :end_meridian%>
  </p>

  <p>
    <%=f.submit%>
  </p>
<% end %>

<%= link_to "Go Back", event_path %>

app/views/events/index.html.erb
<h1>Event Viewer</h1>

<% @events.each do |event| %>
	<h3><%= link_to event.title, event %></h3>
	<p><%= event.start_time %></p>
	<p><%= event.end_time %></p>
<% end %>


<%= link_to "Go Back", home_path %>

app/views/events/new.html.erb
<!-- Shows in events/new -->
<h1>Add Event</h1>
<%= form_for :event, url: events_path do |f| %>
  <p>
    <%=f.label :title%>
    <%=f.text_field :title%>
  </p>

  <p>
    <%=f.label :start_time%>
    <%=f.text_field :start_time%>
  </p>

  <p>
    <%=f.label :start_meridian%>
    <%=f.text_field :start_meridian%>
  </p>

  <p>
    <%=f.label :end_time%>
    <%=f.text_field :end_time%>
  </p>

  <p>
    <%=f.label :end_meridian%>
    <%=f.text_field :end_meridian%>
  </p>

  <p>
    <%=f.submit%>
  </p>
<%end%>

<%= link_to "Go Back", event_path %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<small><%= @event.start_time.strftime("%b %d. %Y %I:%M %p") %></small> 
<p></p>
<small><%= @event.end_time.strftime("%b %d. %Y %I:%M %p") %></small>
<p></p>
<%= link_to "edit", edit_event_path %>
<p>
<%= link_to "Go Back", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whenisbest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>